version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 1234:80
    depends_on:
      - db
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: postgres
        POSTGRES_DB: yeno
    ports:
      - 5432:5432
    networks:
      - react-express
  api:
    image: api
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - react-express
    volumes:
      - ./:/app
  client:
    image: client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - react-express
    volumes:
      - ./:/app
networks:
  react-express:
    driver: bridge

